// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MFiles.PeraniAndPartners.Backend.Models
{
    public partial class Domain
    {
        public string NomeDominioCompleto { get; set; }
        public string NomeDominio { get; set; }
        public DateTime? DataRegistrazione { get; set; }
        public DateTime? DataScadenza { get; set; }
        public string Provider { get; set; }
        public string Registrar { get; set; }
        public string Cliente { get; set; }
        public string Owner { get; set; }
        public string NoteExRegistrar { get; set; }
        public string NoteGenerali { get; set; }
        
        public string Estensione { get; set; }
        public string Stato { get; set; }

    }
}