// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MFiles.PeraniAndPartners.Backend.Models
{
    public partial class IntranetPeraniContext : DbContext
    {
        public IntranetPeraniContext()
        {
        }

        public IntranetPeraniContext(DbContextOptions<IntranetPeraniContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Domain> vw_domainnames { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Domain>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("Domain");

                entity.Property(e => e.Cliente).HasMaxLength(100);

                entity.Property(e => e.Owner).HasMaxLength(100);

                entity.Property(e => e.Provider).HasMaxLength(100);

                entity.Property(e => e.Registrar).HasMaxLength(100);

                entity.Property(e => e.DataRegistrazione)
                    .HasColumnType("datetime")
                    .HasColumnName("DataRegistrazione");

                entity.Property(e => e.DataScadenza)
                    .HasColumnType("datetime")
                    .HasColumnName("DataScadenza");

                entity.Property(e => e.NoteGenerali)
                    .HasColumnType("ntext")
                    .HasColumnName("NoteGenerali");

                entity.Property(e => e.NomeDominio)
                    .HasMaxLength(100)
                    .HasColumnName("NomeDominio");

                entity.Property(e => e.NoteExRegistrar)
                    .HasColumnType("ntext")
                    .HasColumnName("NoteExRegistrar");

                entity.Property(e => e.NomeDominioCompleto)
                   .HasMaxLength(100)
                   .HasColumnName("NomeDominioCompleto");

                entity.Property(e => e.Estensione)
                  .HasMaxLength(100)
                  .HasColumnName("Estensione");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}